name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '36 8,16 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.bvk.rs/kvarovi-na-mrezi/ | head -n -1 > kvarovi-na-mrezi.html
        curl https://www.bvk.rs/planirani-radovi/ | head -n -1 > planirani-radovi.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
